version: '3'

services:
  nodejs:
    container_name: tanya-nodejs
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network
  db:
    image: mongo:4.2
    container_name: tanya-mongo
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
      
networks:
  app-network:
volumes:
  dbdata: